name: Build & Deploy ASP.NET Core API to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_PATH: DreamInCodeApi/DreamInCodeApi.csproj
  PUBLISH_DIR: publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore $PROJECT_PATH

      - name: Build
        run: dotnet build $PROJECT_PATH --configuration Release --no-restore

      - name: Publish
        run: dotnet publish $PROJECT_PATH --configuration Release --no-restore --output $PUBLISH_DIR

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "DreamInCodeApi"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B52EACB298EF472A8BF9C3B432216CC5 }}
          package: ./publish
